#!/bin/bash

# install-deps v1.0.2
# This script is used to install dependencies required by theos.
# Changelog
# v1.0.2 : Add suggenstions for package install errors
# v1.0.1 : Fix curl options
# v1.0.0 : First version

#-------------------------------------------------------------------------------
PLATFORM=`uname -o`
APTGET="apt-get"
declare -a DEPS_ALL=(wget git make perl python)
declare -a DEPS_CYGWIN=(ca-certificates openssh)
declare -a DEPS_LINUX=(ssh)
#declare -a DEPS_DARWIN=(ca-certificates)
#-------------------------------------------------------------------------------
# CURL Options
# -O  : Write output to a file named as the remote file
# -J  : Use the header-provided filename
# -L  : Follow redirects
# -k  : Allow connections to SSL sites without certs
# -s  : Silent mode. Don't output anything
CURLCMD="curl -O -J -L -k -s"
#-------------------------------------------------------------------------------
# UI Functions
HL_NORMAL="\e[39;49m"
HL_YELLOW="\e[30;103m"
HL_RED="\e[97;41m"
FG_GREEN="\e[92m"
FG_YELLOW="\e[93m"

echo_title () {
  local COLS=`expr $(tput cols) - 2`;
  printf "${HL_YELLOW}%-${COLS}s${HL_NORMAL}\n" "$*"
}
echo_info () {
  echo -e "${FG_GREEN}$*${HL_NORMAL}"
}
echo_warning () {
  echo -e "${FG_YELLOW}$*${HL_NORMAL}"
}
echo_n_info () {
  echo -n -e "${FG_GREEN}$*${HL_NORMAL}"
}
echo_error () {
  echo;
  echo -e "${HL_RED}$*${HL_NORMAL}"
  echo;
}
#-------------------------------------------------------------------------------
echo_title " [PRE-CHECK: curl installation]";
if  [ "$PLATFORM" == "Cygwin" ] && ([[ $(cygcheck -c curl | grep OK) != *"OK"* ]]); then
  echo_error "curl is not installed. Please run Cygwin setup again to install curl."
  exit 1;
elif [ "$PLATFORM" != "Cygwin" ] && ([[ $(dpkg-query -W -f='${Status}\n' curl 2>/dev/null | grep ok) != *"ok"* ]]); then
  echo_info "Installing curl..."
  ${APTGET} install curl
  if [[ $? != 0 ]]; then
    echo_error "curl installation failed. Please install manually."
    exit 1;
  else
    echo_info "  Done."
  fi
else
  echo_info "curl is installed and ready."
fi
#-------------------------------------------------------------------------------
echo_title " [PRE-CHECK: apt-get installation]";
if [ "$PLATFORM" ==  "Cygwin" ]; then
  if [ ! -e /bin/apt-cyg ]; then
    echo_info "Downloading apt-cyg..."
    ${CURLCMD} https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg
    if [[ $? != 0 ]]; then
      echo_error "Failed."
      exit 1;
    else
      echo_info "Installing apt-cyg..."
      install ./apt-cyg /bin
      echo_info "Linking apt-cyg to apt-get..."
      ln -s /bin/apt-cyg /bin/apt-get
      rm ./apt-cyg
    fi
  fi
  #APTGET="apt-cyg"
fi
echo_info "apt-get is ready."

#-------------------------------------------------------------------------------
echo_title " [Installing Dependencies...]";
if [ "$PLATFORM" == "Cygwin" ];
then
  declare -a extdeps=${DEPS_CYGWIN[@]}
else
  declare -a extdeps=${DEPS_LINUX[@]}
fi
combined=("${DEPS_ALL[@]}" "${extdeps[@]}" )
for i in ${combined[@]}; do
  echo_info "Checking ${i} installation..."
  if  [ "$PLATFORM" == "Cygwin" ] && ([[ $(cygcheck -c ${i} | grep OK) == *"OK"* ]]); then
    echo_info "  ${i} is already installed."
  elif [ "$PLATFORM" != "Cygwin" ] && ([[ $(dpkg-query -W -f='${Status}\n' ${i} 2>/dev/null | grep ok) == *"ok"* ]]); then
    echo_info "  ${i} is already installed."
  else
    echo_warning "  ${i} is not installed. Initiating install..."
    ${APTGET} install ${i}
    if [[ $? != 0 ]]; then
      echo_error "  ${i} installation failed.  "
      echo_warning "  You may need to run apt-get update to update your package listing."
      if  [ "$PLATFORM" == "Cygwin" ]; then
        echo_warning "  Or run apt-cyg update <mirror url> to add another Cygwin mirror."
        echo;
      fi
      exit 1;
    fi
  fi
done #for
echo_title " [Installing Dependencies...Done.]";
#-------------------------------------------------------------------------------
